package examenpelealab;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Timer;
import java.applet.AudioClip;

/**
 *
 * @author rjcastellanos28
 */
public class pelea extends javax.swing.JFrame {

    /**
     * Creates new form pelea
     */
    public pelea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        knight = new javax.swing.JLabel();
        pollo = new javax.swing.JLabel();
        recuperarKnight = new javax.swing.JButton();
        golpeKnight = new javax.swing.JButton();
        punetazoKnight = new javax.swing.JButton();
        vidaKnight = new javax.swing.JProgressBar();
        vidaPollo = new javax.swing.JProgressBar();
        jugando = new javax.swing.JLabel();
        music = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        knight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenpelealab/knight100x100.png"))); // NOI18N

        pollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenpelealab/basilisk100x100.png"))); // NOI18N

        recuperarKnight.setText("Recuperar");
        recuperarKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                recuperarKnightMousePressed(evt);
            }
        });
        recuperarKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarKnightActionPerformed(evt);
            }
        });

        golpeKnight.setText("Golpe de Espada");
        golpeKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                golpeKnightMousePressed(evt);
            }
        });
        golpeKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golpeKnightActionPerformed(evt);
            }
        });

        punetazoKnight.setText("Puñetazo");
        punetazoKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                punetazoKnightMousePressed(evt);
            }
        });
        punetazoKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punetazoKnightActionPerformed(evt);
            }
        });

        vidaKnight.setValue(100);

        vidaPollo.setValue(100);

        jugando.setText("jLabel1");

        music.setText("Music");
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musicMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(music)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vidaKnight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(recuperarKnight)
                                .addComponent(golpeKnight)
                                .addComponent(punetazoKnight)
                                .addComponent(knight)))
                        .addGap(100, 100, 100)
                        .addComponent(jugando)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vidaPollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pollo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(music)
                        .addGap(20, 20, 20)
                        .addComponent(jugando)
                        .addGap(198, 198, 198))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vidaPollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidaKnight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(knight)
                            .addComponent(pollo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addComponent(recuperarKnight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(golpeKnight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(punetazoKnight)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recuperarKnightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuperarKnightMousePressed
        // TODO add your handling code here:
        double random = Math.random() * 25;
        int nueva_vida = vidaKnight.getValue() + (int) random;
        vidaKnight.setValue(nueva_vida);
        if (nueva_vida <= 0) {
            jugando.setText("Haz Ganado");
        }
        Timer timer = new Timer(1000, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                double ataque_random = Math.random() * 100;

                if (vidaPollo.getValue() == 0) {
                    System.out.print("Dead pollo");
                    return;
                }

                if (ataque_random < 40) {
                    System.out.println("ATAQUE NORMAL");
                    double random = Math.random() * 30;
                    int nueva_vida = vidaKnight.getValue() - (int) random;
                    vidaKnight.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANA EL POLLO");
                    }
                } else if (ataque_random < 80) {
                    System.out.println("CURA");
                    double random = Math.random() * 25;
                    int nueva_vida = vidaPollo.getValue() + (int) random;
                    vidaPollo.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANA EL POLLO");
                    }
                } else if (ataque_random < 90) {
                    System.out.println("ATAQUE: 2");
                    double random = Math.random() * 90;
                    int nueva_vida = vidaPollo.getValue() - (int) random;
                    vidaKnight.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANA EL POLLO");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();

    }//GEN-LAST:event_recuperarKnightMousePressed

    private void golpeKnightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_golpeKnightMousePressed
        // TODO add your handling code here:
        int random = 17;
        int nueva_vida = vidaPollo.getValue() - random;
        vidaPollo.setValue(nueva_vida);
        if (nueva_vida <= 0) {
            jugando.setText("GANASTE");
        }
        Timer timer = new Timer(1000, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                double ataque_random = Math.random() * 100;

                if (ataque_random < 40) {
                    System.out.println("ATAQUE: NORMAL"
                            + "");
                    double random = Math.random() * 30;
                    int nueva_vida = vidaKnight.getValue() - (int) random;
                    vidaKnight.setValue(nueva_vida);
            
                    if (nueva_vida <= 0) {
                        jugando.setText("GANO EL KNIGHT");
                    }
                } else if (ataque_random < 80) {
                    System.out.println("CURA");
                    double random = Math.random() * 25;
                    int nueva_vida = vidaPollo.getValue() + (int) random;
                    vidaPollo.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANO EL POLLO MUTANTE");
                    }
                } else if (ataque_random < 90) {
                    System.out.println("ATAQUE: 2");
                    int nueva_vida = vidaPollo.getValue() + (int) random;
                    vidaKnight.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANO EL POLLO MUTANTE");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();

    }//GEN-LAST:event_golpeKnightMousePressed

    private void golpeKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golpeKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_golpeKnightActionPerformed

    private void punetazoKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punetazoKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punetazoKnightActionPerformed

    private void recuperarKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recuperarKnightActionPerformed

    private void punetazoKnightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_punetazoKnightMousePressed
        // TODO add your handling code here:
        double random = Math.random() * 90;
        int nueva_vida = vidaPollo.getValue() - (int) random;
        vidaPollo.setValue(nueva_vida);
        if (nueva_vida <= 0) {
            jugando.setText("GANASTE");
            return;
        }

        Timer timer = new Timer(1000, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                double ataque_random = Math.random() * 100;
                if (vidaPollo.getValue() == 0) {
                    System.out.print("Dead pollo");
                    return;
                }

                if (ataque_random < 40) {
                    System.out.println("ATAQUE: NORMAL");
                    double random = Math.random() * 30;
                    int nueva_vida = vidaKnight.getValue() - (int) random;
                    vidaKnight.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANO EL KNIGHT");
                    }
                } else if (ataque_random < 80) {
                    System.out.println("SE CURA");
                    double random = Math.random() * 25;
                    int nueva_vida = vidaPollo.getValue() + (int) random;
                    vidaPollo.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANO EL POLLO MUTANTE");
                    }
                } else if (ataque_random < 90) {
                    System.out.println("ATAQUE: 2");
                    double random = Math.random() * 90;
                    int nueva_vida = vidaPollo.getValue() - (int) random;
                    vidaKnight.setValue(nueva_vida);
                    if (nueva_vida <= 0) {
                        jugando.setText("GANO EL POLLO MUTANTE");
                    }
                }
            }

        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_punetazoKnightMousePressed

    private void musicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMousePressed
        // TODO add your handling code here:
        AudioClip musicapelea;
        musicapelea = java.applet.Applet.newAudioClip(getClass().getResource("/examenPeleaLab/musicpelea.wav"));
        musicapelea.play();
    }//GEN-LAST:event_musicMousePressed
//TERMINA ATAQUE 1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton golpeKnight;
    private javax.swing.JLabel jugando;
    private javax.swing.JLabel knight;
    private javax.swing.JButton music;
    private javax.swing.JLabel pollo;
    private javax.swing.JButton punetazoKnight;
    private javax.swing.JButton recuperarKnight;
    private javax.swing.JProgressBar vidaKnight;
    private javax.swing.JProgressBar vidaPollo;
    // End of variables declaration//GEN-END:variables
}
